### ISSUE TITLE
Cleanup - Change /ploigos/generated-psr to /ploigos/psr-secrets.yml

### ISSUE THREAD

**Issue by dwinchell** [ploigos/ploigos-github-workflows#28]
Success Criteria:
* ploigos-github-workflows reads its shared configuration from a file named /psr-secrets.yml instead of /ploigos/generated-psr
* The infra-ops repo has been updated to mount a secret at the new location

**Comment by aarongreen85** [comment]
Possibly will be done as part of https://github.com/ploigos/infra-ops/issues/34. Adding to sprint in case.

**Comment by aarongreen85** [comment]
Was done as part of #34.
