### ISSUE TITLE
Break out psr steps into separate jobs

### ISSUE THREAD

**Issue by aarongreen85** [ploigos/ploigos-github-workflows#42]
Success criteria:
There are at minimum separate jobs for setup, image, deploy, and report.

**Comment by aarongreen85** [comment]
Thoughts during implementing. Does this break the upgrade of psr in the workflow? If I understand correctly, that step will run on a container and then when the next job kicks off another pod will likely run through those steps, which won't have the upgraded psr? It'll get the psr version that is part of the container image?

**Comment by dwinchell** [comment]
Good point. If we want to download the psr in an action AND split the pipeline into multiple jobs, we need to do this: https://docs.github.com/en/actions/creating-actions/developing-a-third-party-cli-action

We could also take out the upgrade and see how annoying that becomes. So far we haven't had to do much hacking on the PSR.
